### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' (ä) with 1.8.6

### ISSUE THREAD

**Issue by agitator** [plone/plone.subrequest#21]
With the latest 1.8.6 release which included the py3 fixes I get the following error within a mosaic page that contains raw html.

```
2018-11-16 15:53:35 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/Users/peter/workspace/sba/eggs/plone.transformchain-2.0.0-py2.7.egg/plone/transformchain/transformer.py", line 59, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/Users/peter/workspace/sba/eggs/plone.app.blocks-4.1.1-py2.7.egg/plone/app/blocks/transform.py", line 166, in transformIterable
    result.tree = tiles.renderTiles(self.request, result.tree)
  File "/Users/peter/workspace/sba/eggs/plone.app.blocks-4.1.1-py2.7.egg/plone/app/blocks/tiles.py", line 73, in renderTiles
    tileTree = utils.resolve(tileHref)
  File "/Users/peter/workspace/sba/eggs/plone.app.blocks-4.1.1-py2.7.egg/plone/app/blocks/utils.py", line 73, in resolve
    resolved = resolveResource(url)
  File "/Users/peter/workspace/sba/eggs/plone.app.blocks-4.1.1-py2.7.egg/plone/app/blocks/utils.py", line 115, in resolveResource
    response = subrequest(url, exception_handler=subresponse_exception_handler)
  File "/Users/peter/workspace/sba/eggs/plone.subrequest-1.8.6-py2.7.egg/plone/subrequest/__init__.py", line 170, in subrequest
    logger.exception('Error handling subrequest to {0}'.format(url))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 676: ordinal not in range(128)

```

Bug? Feature? ... ?
@pbauer any idea?

**Comment by petschki** [comment]
this is fixed in 1.9.0 ... I've adapted the version in plone.app.mosaic's install_requires accordingly
